condense_wildcard_suffixes = true
fn_single_line = true
merge_imports = true
match_block_trailing_comma = true
max_width = 80
reorder_impl_items = true
struct_field_align_threshold = 30
use_field_init_shorthand = true
